### ISSUE TITLE
Test wire adapters should filter based on config

### ISSUE THREAD

**Issue by trevor-bliss** [salesforce/wire-service-jest-util#15]
The current logic in the test adapter `emit` functions sends data to all matching wire adapters, regardless of the config of the wire adapter. 

This is a problem if there are multiple wire adapters connected with different configs since there is no way to emit data to one adapter but not the other.

In the example below, this tool provides no way to emit data to only one of the `@wire` functions.

```
@wire(getRecord, { recordId: '$recordId', ['Account.Name']})
accountData(data, error){
    // do something with an account
}

@wire(getRecord, { recordId: '$recordId', ['Contact.Name']})
contactData({data}){
    // do something with a contact
}
```

**Comment by kcappieg** [comment]
I came across this problem while testing my first lwc that used wire functions. It uses 2 `getRecord` wires for different object types.

I looked through the code a bit and I think the fix would be pretty easy. Just add a `params` argument to both `emit` and `error` that the function matches against the value of `wiredEventTarget._wireDef.params`.

Making that parameter optional wouldn't break the public API.
If we don't want to reach into that component, then we'd additionally have to modify that class (in `@lwc/wire-service` to expose a getter for those parameters to match against.

Thoughts? Questions? I just glanced through the code for about 20 minutes, so let me know if there's something I'm missing

**Comment by trevor-bliss** [comment]
Thanks @kcappieg for doing some digging. I agree the fix won't be too complex. Instead of matching against `wiredEventTarget._wireDef.params`, I was thinking we could leverage the `config` event handler to know which wire has a matching config when we emit.

https://github.com/salesforce/wire-service-jest-util/blob/master/src/adapters/lds.js#L80

We should get to this Issue soon. Stay tuned.

**Comment by sjonwilson** [comment]
I have exactly the same problem. It doesn't seem hard to do. I took a copy of the code and just needed to change:

**Comment by trevor-bliss** [comment]
**Status Update**

Internally, we're still in the middle of some non-trivial changes to the way the wire service and the wire adapters interact. In terms of component functionality for platform provided wire adapters like `getRecord`, these changes should be transparent to the end user.

We're still very aware of this issue and as soon as the internals of the wire service settle we will tackle this test utility gap. 

cc/ @jodarove

**Comment by NathanWenslaff** [comment]
We have run into this issue as well. Has there been a status update?

**Comment by yyutianzheng** [comment]
why is getRecordWireAdapter.emit() not returning a promise. I am testing my component with is method, but I need to do a setTimeout() to make sure the component gets updated

**Comment by BatemanVO** [comment]
I see that there's a pull request for this issue, but I couldn't tell from looking it over whether the actual problem has been resolved. A developer on our team ran into the same issue today where two `@wire`-decorated calls to `getRecord` were ultimately setting the same value for both decorated properties in tests.

Our only workaround, since the two objects had completely different fields being referenced, was to `.emit()` an object that had all the necessary properties.

For example, we needed to reference Case and User, and we ended up `.emit()`ing an object that had a `.fields` property that then had fields for both Case and User, so that when the implementation logic referenced Case fields, they would exist, and when the implementation logic referenced User fields, they would exist.

It seems hacky and it has the limitation of only being able to reference fields if both objects don't share the same API name for any field.

**Comment by jodarove** [comment]
@BatemanVO this is resolved on v3.x of the library. You can use the second argument of the `emit` method to control which instance of the wire adapter should receive the value. Ex:

```js
    @wire(getRecord, { recordId: '1' }) recordOne;

    @wire(getRecord, { recordId: '2' }) recordTwo;
```

```js
     getRecord.emit({ data: 'for record one' }, (config) => config.recordId === '1');

     getRecord.emit({ data: 'for record two' }, (config) => config.recordId === '2');
```

**Comment by ramdevchahar** [comment]
> @BatemanVO this is resolved on v3.x of the library. You can use the second argument of the `emit` method to control which instance of the wire adapter should receive the value. Ex:
> 
> ```js
>     // Your component under test code.
>     @wire(getRecord, { recordId: '1' }) recordOne;
> 
>     @wire(getRecord, { recordId: '2' }) recordTwo;
> ```
> 
> ```js
>      // Your test code
>      getRecord.emit({ data: 'for record one' }, (config) => config.recordId === '1');
> 
>      getRecord.emit({ data: 'for record two' }, (config) => config.recordId === '2');
> ```

Could you please explain this in detail? or share the reference link.
