### ISSUE TITLE
Apex test wire adapter's emit() method should correctly shape data

### ISSUE THREAD

**Issue by jcory** [salesforce/wire-service-jest-util#24]
It appears that the emit method of the apex test wire adapter is no longer using the correct shape (`{ data: undefined, error: err }`)

If I have a LWC with the following code:

<pre><code>@wire(getFoo)
wiredGetFoo(result) {
    const { data } = result;
    if (data) {
        this.bar = data.map((bar) => ({ ...bar }));
    }
}</code></pre>

And a jest test that mocks the wire adapter and emits the contents of a .json file:

<pre><code>import { registerApexTestWireAdapter } from '@salesforce/sfdx-lwc-jest';
import getFoo from '@salesforce/apex/FooController.getFoo';
const getFooWireAdapter = registerApexTestWireAdapter(getFoo);
const mockGetFoo = require('./data/getFoo.json');
...
getFooWireAdapter.emit(mockGetFoo);</code></pre>

We find that `result.data` is undefined. This started happening a few nights ago, which would seem to correspond with this commit [https://github.com/salesforce/wire-service-jest-util/commit/d363073d3735b17bd5659cf00ce35cba9ea1f70d](url).

To verify this was the issue, I wrapped the contents of the .json file in a "data" attribute and verified that the test passed (as it had previously).

**Comment by jodarove** [comment]
fixed with #26

**Comment by jodarove** [comment]
fyi/ @jcory

**Comment by jodarove** [comment]
please use v2.4.2, since 2.4.1 is faulty.
