### ISSUE TITLE
What is the equivalent of getRecordAdapter.error() ?

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/wire-service-jest-util#51]
Since `registerLdsTestWireAdapter` is [deprecated](https://github.com/salesforce/wire-service-jest-util/blob/master/docs/migrating-from-version-2.x-to-3.x.md), what is the equivalent of `getRecordAdapter.error();`

````js
import { getRecord } from 'lightning/uiRecordApi';
import { registerLdsTestWireAdapter } from '@salesforce/sfdx-lwc-jest';
const getRecordAdapter = registerLdsTestWireAdapter(getRecord);

...

 getRecordAdapter.error();
...
````

I can't do `getRecord.emit()` to resolve into `error` because it is only used to return the `data` key. So, what should I do? Or if it is possible, could you give an example of how I make it return the mock data into the `error` key?

**Comment by jodarove** [comment]
@AllanOricil you should be able to call `.error()` on `getRecord`, that's not the case for you?

[Here](https://github.com/trailheadapps/lwc-recipes/blob/f9c702aeacea07f58d2d8505c3a92d902de550fd/force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/lmsSubscriberWebComponent.test.js#L132-L153) is an example from the [lwc-recipes repo](https://github.com/trailheadapps/lwc-recipes).

Note: In an sfdx projects, all lightning modules should be mocked, and `getRecord` from `lightning/uiRecordApi` should resolve to the result of [`createLdsTestWireAdapter`](https://github.com/salesforce/wire-service-jest-util#createldstestwireadapter); unless  it is manually mocked on the  are overridden in the [sfdx jest configuration](https://github.com/trailheadapps/lwc-recipes/blob/f9c702aeacea07f58d2d8505c3a92d902de550fd/jest.config.js)

**Comment by AllanOricil** [comment]
> @AllanOricil you should be able to call `.error()` on `getRecord`, that's not the case for you?
> 
> [Here](https://github.com/trailheadapps/lwc-recipes/blob/f9c702aeacea07f58d2d8505c3a92d902de550fd/force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/lmsSubscriberWebComponent.test.js#L132-L153) is an example from the [lwc-recipes repo](https://github.com/trailheadapps/lwc-recipes).
> 
> Note: In an sfdx projects, all lightning modules should be mocked, and `getRecord` from `lightning/uiRecordApi` should resolve to the result of [`createLdsTestWireAdapter`](https://github.com/salesforce/wire-service-jest-util#createldstestwireadapter); unless it is manually mocked on the are overridden in the [sfdx jest configuration](https://github.com/trailheadapps/lwc-recipes/blob/f9c702aeacea07f58d2d8505c3a92d902de550fd/jest.config.js)

I didn't not try it. Tomorrow I will test and share the result with you
